### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by oagarcia** [mmratio/roku-deploy#3]
Mike, I got this in 7.2 :(
1. Build

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: [roku-deploy](https://github.com/mmratio/roku-deploy) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'statusCode' of undefined

```
At /Users/andresgarcia/.atom/packages/roku-deploy/lib/roku-deploy.coffee:111

TypeError: Cannot read property 'statusCode' of undefined
    at Request.module.exports.RokuDeploy.requestCallback [as _callback] (/Users/andresgarcia/.atom/packages/roku-deploy/lib/roku-deploy.coffee:111:27)
    at self.callback (/Users/andresgarcia/.atom/packages/roku-deploy/node_modules/request/request.js:199:22)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/andresgarcia/.atom/packages/roku-deploy/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
### Commands

```
     -3:17 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:17 settings-view:view-installed-packages (atom-text-editor.editor)
     -2:16.2.0 core:copy (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:46.2.0 core:backspace (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:45.8.0 core:paste (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:43.3.0 core:cut (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:39.6.0 core:paste (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:39 core:backspace (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:38.3.0 editor:select-to-first-character-of-line (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:37.9.0 core:move-left (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
  7x -1:37.7.0 core:select-right (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:36.6.0 core:backspace (atom-text-editor#roku-deploy.rokuAddress.editor.mini.is-focused)
     -1:18 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:18 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -1:02.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:31 roku-deploy:deployRoku (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.js.jsx.react": [
        "jsx"
      ]
    },
    "disabledPackages": [
      "linter-jshint",
      "vim-mode",
      "angularjs",
      "atom-beautify",
      "atom-handlebars",
      "atom-json-editor",
      "atom-typescript",
      "auto-detect-indentation",
      "color-picker",
      "language-babel",
      "language-javascript-jsx",
      "linter-php",
      "linter-pylint",
      "react",
      "react-es6-snippets",
      "react-snippets",
      "terminal-plus"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "roku-deploy": {
    "excludedPaths": "out,tools",
    "rokuAddress": "192.168.21.220"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.13.2
docblockr, v0.7.3
emmet, v2.4.3
file-type-icons, v1.0.1
file-types, v0.5.1
formatter-json, v1.0.1
highlight-selected, v0.11.2
indentation-indicator, v0.6.0
json-colorer, v0.3.0
json-schema, v0.1.15
language-brightscript, v0.6.1
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.1.3
linter-golinter, v1.2.0
linter-htmlhint, v1.1.1
linter-jscs, v3.4.10
linter-jsonlint, v1.2.2
linter-sass-lint, v1.3.0
linter-scss-lint, v2.5.1
linter-tslint, v0.9.0
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
pigments, v0.26.0
pretty-json, v0.4.1
roku-deploy, v0.3.1
seti-ui, v0.9.2

# Dev
No dev packages
```

**Comment by oagarcia** [comment]
Closing as I figured out that it is related to the same issue already reported about ip not updated unless you restart Atom
